### ISSUE TITLE
似乎不太准确，这句的描述，require_recipient触发通知

### ISSUE THREAD

**Issue by HashDApp** [slowmist/eos-smart-contract-security-best-practices#2]
> require_recipient(account_name name) 可触发通知，调用name合约中的同名函数，官方文档

并不是一定会有合约部署在name下

**Comment by keywolf** [comment]
> > require_recipient(account_name name) 可触发通知，调用name合约中的同名函数，官方文档
> 
> 并不是一定会有合约部署在name下

是的，我把假设条件加上去，感谢反馈 👍

**Comment by HashDApp** [comment]
> > > require_recipient(account_name name) 可触发通知，调用name合约中的同名函数，官方文档
> > 
> > 
> > 并不是一定会有合约部署在name下
> 
> 是的，我把假设条件加上去，感谢反馈

感觉还是不太准确
有action就可以了
函数名倒无所谓
