### ISSUE TITLE
Invalid Link

### ISSUE THREAD

**Issue by ultrasilicon** [slowmist/eos-smart-contract-security-best-practices#6]
## Description
In section "随机数实践", The link to "Randomization in Contracts", which is `https://developers.eos.io/eosio-cpp/docs/random-number-generation` is not valid (404 not found) any more.

**Comment by keywolf** [comment]
Thanks

**Comment by gleehokie** [comment]
@keywolf we removed that section of the developer docs since **on-chain** PRNG is not possible with EOSIO.

**Comment by ultrasilicon** [comment]
Okay, good to know. Thanks guys!
